print('hello')
print("what's your name?")
myName = input()
print("it's nice to meet you, " + myName)
print ("the length of your name is:")
print(len(myName))
print("what's your age?")
myAge = input()
print('You will be ' + str(int(myAge) + 1) + ' in a year.')
